/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokemojuego;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class SeleccionaPokemon extends javax.swing.JFrame {

    private ListaEnlazada<JLabel> pokemonesSeleccionados;
    private ListaEnlazada<ListaEnlazada<JLabel>> equiposCPU;

    /**
     * Creates new form SeleccionPokemon
     */
    public SeleccionaPokemon() {
        pokemonesSeleccionados = new ListaEnlazada<>();
        equiposCPU = new ListaEnlazada<>(); // Inicializar equipos de la CPU
        initComponents();
        setupEventHandlers();
        jButton1.setEnabled(false);  // Deshabilitar el botón "EMPEZAR" al inicio.
    }

    private void setupEventHandlers() {
        // Asignar eventos de clic a los JLabels en un método que puedas editar
        Mudkip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarPokemon(Mudkip, "Mudkip");
            }
        });

        Seel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarPokemon(Seel, "Seel");
            }
        });

        Squirtle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarPokemon(Squirtle, "Squirtle");
            }
        });

        Torchic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarPokemon(Torchic, "Torchic");
            }
        });

        Cyndaquil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarPokemon(Cyndaquil, "Cyndaquil");
            }
        });

        Charmander.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarPokemon(Charmander, "Charmander");
            }
        });

        Jigglypuff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarPokemon(Jigglypuff, "Jigglypuff");
            }
        });

        Pidgeot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarPokemon(Pidgeot, "Pidgeot");
            }
        });

        Rattata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarPokemon(Rattata, "Rattata");
            }
        });
    }

    private void seleccionarPokemon(JLabel label, String nombrePokemon) {
        if (pokemonesSeleccionados.size() < 3) {
            if (!pokemonesSeleccionados.contains(label)) {
                pokemonesSeleccionados.add(label);  // Almacena el JLabel completo
                label.setEnabled(false);  // Deshabilitar el label después de seleccionarlo.
                if (pokemonesSeleccionados.size() == 3) {
                    jButton1.setEnabled(true);  // Habilitar el botón "EMPEZAR".
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ya has seleccionado 3 Pokémon.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mudkip = new javax.swing.JLabel();
        Seel = new javax.swing.JLabel();
        Squirtle = new javax.swing.JLabel();
        Torchic = new javax.swing.JLabel();
        Cyndaquil = new javax.swing.JLabel();
        Charmander = new javax.swing.JLabel();
        Jigglypuff = new javax.swing.JLabel();
        Pidgeot = new javax.swing.JLabel();
        Rattata = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mudkip.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Mudkip.setForeground(new java.awt.Color(255, 255, 255));
        Mudkip.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://images.wikidexcdn.net/mwuploads/wikidex/thumb/a/ae/latest/20230706064339/Mudkip.png/300px-Mudkip.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        Mudkip.setText("Mudkip ");
        getContentPane().add(Mudkip, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 400, -1, -1));

        Seel.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Seel.setForeground(new java.awt.Color(255, 255, 255));
        Seel.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://images.wikidexcdn.net/mwuploads/wikidex/thumb/f/f1/latest/20230627050530/Seel.png/300px-Seel.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        Seel.setText("Seel ");
        getContentPane().add(Seel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        Squirtle.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Squirtle.setForeground(new java.awt.Color(255, 255, 255));
        Squirtle.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://images.wikidexcdn.net/mwuploads/wikidex/thumb/e/e3/latest/20160309230820/Squirtle.png/300px-Squirtle.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        Squirtle.setText("Squirtle ");
        getContentPane().add(Squirtle, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        Torchic.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Torchic.setForeground(new java.awt.Color(255, 255, 255));
        Torchic.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://images.wikidexcdn.net/mwuploads/wikidex/thumb/4/4f/latest/20230706064856/Torchic.png/300px-Torchic.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        Torchic.setText("Torchic ");
        getContentPane().add(Torchic, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 460, -1));

        Cyndaquil.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Cyndaquil.setForeground(new java.awt.Color(255, 255, 255));
        Cyndaquil.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://images.wikidexcdn.net/mwuploads/wikidex/thumb/9/99/latest/20200307021608/Cyndaquil.png/300px-Cyndaquil.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        Cyndaquil.setText("Cyndaquil ");
        getContentPane().add(Cyndaquil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 190, -1, -1));

        Charmander.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Charmander.setForeground(new java.awt.Color(255, 255, 255));
        Charmander.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://images.wikidexcdn.net/mwuploads/wikidex/thumb/5/56/latest/20200307023245/Charmander.png/300px-Charmander.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        Charmander.setText("Charmander ");
        getContentPane().add(Charmander, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 550, -1));

        Jigglypuff.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Jigglypuff.setForeground(new java.awt.Color(255, 255, 255));
        Jigglypuff.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://images.wikidexcdn.net/mwuploads/wikidex/thumb/a/af/latest/20150110232910/Jigglypuff.png/300px-Jigglypuff.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        Jigglypuff.setText("Jigglypuff");
        getContentPane().add(Jigglypuff, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 510, -1));

        Pidgeot.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Pidgeot.setForeground(new java.awt.Color(255, 255, 255));
        Pidgeot.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://images.wikidexcdn.net/mwuploads/wikidex/thumb/a/a9/latest/20141214190416/Pidgeot.png/300px-Pidgeot.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        Pidgeot.setText("Pidgeot");
        getContentPane().add(Pidgeot, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 460, -1));

        Rattata.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Rattata.setForeground(new java.awt.Color(255, 255, 255));
        Rattata.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://images.wikidexcdn.net/mwuploads/wikidex/thumb/c/c4/latest/20200307022853/Rattata.png/300px-Rattata.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        Rattata.setText("Rattata");
        getContentPane().add(Rattata, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 460, -1));

        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 670, 380, 120));

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdna.artstation.com/p/assets/images/images/077/352/672/large/flyziken-twitch-bg-pokemon.jpg?1719247264")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JLabel[] todosLosPokemones = {Mudkip, Seel, Squirtle, Torchic, Cyndaquil, Charmander, Jigglypuff, Pidgeot, Rattata};

        // Crear una lista temporal para seleccionar Pokémon únicos
        ListaEnlazada<JLabel> pokemonesDisponibles = new ListaEnlazada<>();
        for (JLabel pokemon : todosLosPokemones) {
            pokemonesDisponibles.add(pokemon);
        }

        // Dividir los 9 Pokémon en 3 equipos
        for (int i = 0; i < 3; i++) {
            ListaEnlazada<JLabel> equipo = new ListaEnlazada<>();
            for (int j = 0; j < 3; j++) {
                // Seleccionar aleatoriamente un Pokémon de los disponibles
                int indiceAleatorio = (int) (Math.random() * pokemonesDisponibles.size());
                equipo.add(pokemonesDisponibles.get(indiceAleatorio));

                // Remover el Pokémon seleccionado para evitar repeticiones
                pokemonesDisponibles.remove(indiceAleatorio);
            }
            equiposCPU.add(equipo);
            // Imprimir los nombres de los Pokémon del equipo actual en la consola
            System.out.println("Equipo " + (i + 1) + ":");
            for (int k = 0; k < equipo.size(); k++) {
                System.out.println(" - " + equipo.get(k).getText());
            }
        }

        // Crear instancia de Combate con los Pokémon seleccionados por el usuario y los equipos de la CPU
        Combate combate = new Combate(pokemonesSeleccionados, equiposCPU);

        // Configurar la ventana para que aparezca en el centro de la pantalla
        combate.setLocationRelativeTo(null);
        combate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionaPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Charmander;
    private javax.swing.JLabel Cyndaquil;
    private javax.swing.JLabel Jigglypuff;
    private javax.swing.JLabel Mudkip;
    private javax.swing.JLabel Pidgeot;
    private javax.swing.JLabel Rattata;
    private javax.swing.JLabel Seel;
    private javax.swing.JLabel Squirtle;
    private javax.swing.JLabel Torchic;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
